image: alpine:latest

variables:
  CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA

stages:
  - Build
  - Tag
  - Deploy
  - Legacy

.build:
  stage: Build
  except:
    - tags
  when: manual
  variables:
    CI_DEBUG_TRACE: "true"
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${HARBOR_HOST}\":{\"auth\":\"$(echo -n ${HARBOR_USERNAME}:${HARBOR_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${DOCKER_FILE}"
      --destination "${HARBOR_HOST}/${HARBOR_PROJECT}/${CI_PROJECT_NAME}-${APP}:${CI_COMMIT_SHORT_SHA}"

Build app zalo-server:
  extends: .build
  variables:
    APP: zalo-server
    DOCKER_FILE: Dockerfile

.deploy_production:
  stage: Deploy
  when: manual
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOYER_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p$HOST_PORT $HOST_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

Tag zalo-server:
  stage: Tag
  only:
    - tags
  extends: .deploy_production
  variables:
    APP: zalo-server
  script:
    - ssh -p$HOST_PORT $DEPLOYER_USER@$HOST_IP "docker pull ${HARBOR_HOST}/${HARBOR_PROJECT}/${CI_PROJECT_NAME}-${APP}:${CI_COMMIT_SHORT_SHA} && docker tag ${HARBOR_HOST}/${HARBOR_PROJECT}/${CI_PROJECT_NAME}-${APP}:${CI_COMMIT_SHORT_SHA} ${HARBOR_HOST}/${HARBOR_PROJECT}/${CI_PROJECT_NAME}-${APP}:${CI_COMMIT_TAG}"

Deploy app zalo-server production:
  stage: Deploy
  only:
    - tags
  extends: .deploy_production
  when: manual
  needs:
    - Tag zalo-server
  variables:
    APP: zalo-server
    DOCKER_COMPOSE_FILE: docker-compose-habor.yaml
  script:
    - ssh -p$HOST_PORT $DEPLOYER_USER@$HOST_IP "export IMAGE_TAG=$CI_COMMIT_TAG && cd $SERVICE_PATH && git checkout main && git pull origin main && docker compose --file ${DOCKER_COMPOSE_FILE} up -d"

deploy_production:
  stage: Legacy
  when: manual
  extends: .deploy_production
  script:
    - ssh -p$HOST_PORT $DEPLOYER_USER@$HOST_IP " cd $SERVICE_PATH && git checkout main && git pull origin main && docker compose up -d --force-recreate --build zalo-server"
  only:
    - main